version: '3.8'

services:
  app:
    image: myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:80" # Map le port 80 (Kestrel) de l'app sur le port 5000 du host
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourSecurePassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" # Expose SQL Server pour des outils de debug ou d'administration
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge